version: '3'

services:
  mysql:
    container_name: todo_database
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_USER: "root"
      MYSQL_DATABASE: "todo4"
  application:
    container_name: todo_service
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    ports:
      - 3030:3030
